@startuml
start
:Загрузка данных;
if ( данные успешно загрузились?) then (Нет)
:ошибка соединения;
stop
else (Да)
:Проверка данных;
if ( данные содержат ошибки?) then (Да)
:выдать информацию об ошибках 
(некорректный формат, пропуски);
stop
else (Нет)
:Обработка данных;
repeat :Формирование отчета;
if (Отчет сформирован?) then (Нет)
:повторить попытку формирования;
else (Да)
break
endif
repeat while (Отчет сформирован?) is (Нет)
fork
:Отправка отчета;
fork again
:Сохранение отчета;
end fork
stop
@enduml


